fix deploy versiones nuevas

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,29 +16,39 @@ concurrency:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-
-    # Definimos que todos los comandos se ejecuten dentro de tu carpeta 'Portfolio'
-    defaults:
-      run:
-        working-directory: Portfolio
-
+    runs-on: ubuntu-latest # Actualizado a la versión más reciente
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT # 1. CAMBIADO: de 'ci' a 'install' para forzar la descarga de Svelte
+            echo "runner=npm run" >> $GITHUB_OUTPUT # 2. CAMBIADO: para usar los scripts locales
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: "22" # Requisito para Astro 6
-
+          node-version: "22" # 3. CAMBIADO: de '20' a '22' (Requisito de Astro 6)
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v5
       - name: Install dependencies
-        # Al estar en el working-directory, leerá el package.json que acabas de fusionar
-        run: npm install
-
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
       - name: Build with Astro
-        run: npm run build
-
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} build
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
